### ISSUE TITLE
Dependency on Java 9

### ISSUE THREAD

**Issue by mfirry** [DanSimon/scalene#3]
Hi, this seems like a nice library.

Just one curiosity: `java.util.Arrays.mismatch` is used in `HttpRequest`. This method was introduced in Java 9 (I just discovered about it, by the way).

Was this choice done on purpose?

Thanks

**Comment by DanSimon** [comment]
Hey, yeah it's just an optimization, certainly not necessary but it works well.  I wouldn't say I intentionally required Java >= 9, but considering that Java 8 is pretty old at this point I think it's reasonable to require something newer.

I've been developing with Java 12/13 but I'll probably be targeting Java 11 going forward since it's LTS.

**Comment by mfirry** [comment]
Cool thanks!
